CITY_DICT = {u'Canada': u'#CA', 
	u'richmond ': u'richmondin.craigslist.org/', 
	u'cincinnati': u'cincinnati.craigslist.org/', 
	u'guelph': u'guelph.craigslist.ca/', 
	u'kamloops': u'kamloops.craigslist.ca/', 
	u'merced': u'merced.craigslist.org/', 
	u'nottingham': u'nottingham.craigslist.co.uk/', 
	u'salvador, bahia': u'salvador.craigslist.org/', 
	u'bellingham': u'bellingham.craigslist.org/', 
	u'bangladesh': u'bangladesh.craigslist.org/', 
	u'the thumb': u'thumb.craigslist.org/', 
	u'roanoke': u'roanoke.craigslist.org/', 
	u'christchurch': u'christchurch.craigslist.org/', 
	u'lille': u'lille.craigslist.org/', 
	u'bismarck': u'bismarck.craigslist.org/', 
	u'farmington': u'farmington.craigslist.org/', 
	u'wyoming': u'wyoming.craigslist.org/', 
	u'lucknow': u'lucknow.craigslist.co.in/', 
	u'huntington-ashland': u'huntington.craigslist.org/', 
	u'kootenays': u'kootenays.craigslist.ca/', 
	u'duluth': u'duluth.craigslist.org/',
	u'superior': u'duluth.craigslist.org/',  
	u'venice': u'venice.craigslist.it/',
	u'veneto': u'venice.craigslist.it/', 
	u'devon & cornwall': u'devon.craigslist.co.uk/', 
	u'orange county': u'orangecounty.craigslist.org/', 
	u'mendocino county': u'mendocino.craigslist.org/', 
	u'montevideo': u'montevideo.craigslist.org/', 
	u'ghana': u'accra.craigslist.org/', 
	u'beirut, lebanon': u'beirut.craigslist.org/', 
	u'sherbrooke': u'sherbrooke.craigslist.ca/', 
	u'tulsa': u'tulsa.craigslist.org/', 
	u'wausau': u'wausau.craigslist.org/', 
	u'southwest MN': u'marshall.craigslist.org/', 
	u'nanaimo': u'nanaimo.craigslist.ca/', 
	u'muskegon': u'muskegon.craigslist.org/', 
	u'dothan': u'dothan.craigslist.org/', 
	u'syracuse': u'syracuse.craigslist.org/', 
	u'east midlands': u'eastmids.craigslist.co.uk/', 
	u'pueblo': u'pueblo.craigslist.org/', 
	u'columbia / jeff city': u'columbiamo.craigslist.org/', 
	u'hawaii': u'honolulu.craigslist.org/', 
	u'puebla': u'puebla.craigslist.com.mx/', 
	u'alicante': u'alicante.craigslist.es/', 
	u'moses lake': u'moseslake.craigslist.org/', 
	u'ft mcmurray': u'ftmcmurray.craigslist.ca/', 
	u'bozeman': u'bozeman.craigslist.org/', 
	u'la salle co': u'lasalle.craigslist.org/', 
	u'scranton / wilkes-barre': u'scranton.craigslist.org/', 
	u'albany ': u'albanyga.craigslist.org/', 
	u'dresden': u'dresden.craigslist.de/', 
	u'copenhagen': u'copenhagen.craigslist.org/', 
	u'space coast': u'spacecoast.craigslist.org/', 
	u'north mississippi': u'northmiss.craigslist.org/', 
	u'southwest TX': u'bigbend.craigslist.org/', 
	u'gold coast': u'goldcoast.craigslist.com.au/', 
	u'chicago': u'chicago.craigslist.org/', 
	u'panama': u'panama.craigslist.org/', 
	u'tri-cities': u'tricities.craigslist.org/', 
	u'maine': u'maine.craigslist.org/', 
	u'richmond': u'richmond.craigslist.org/', 
	u'virgin islands': u'virgin.craigslist.org/', 
	u'sheffield': u'sheffield.craigslist.co.uk/', 
	u'dallas / fort worth': u'dallas.craigslist.org/', 
	u'colorado springs': u'cosprings.craigslist.org/', 
	u'canarias': u'canarias.craigslist.es/', 
	u'harrisonburg': u'harrisonburg.craigslist.org/', 
	u'osaka-kobe-kyoto': u'osaka.craigslist.jp/', 
	u'loire valley': u'loire.craigslist.org/', 
	u'guangzhou': u'guangzhou.craigslist.com.cn/', 
	u'okinawa': u'okinawa.craigslist.jp/', 
	u'wuhan': u'wuhan.craigslist.com.cn/', 
	u'cebu': u'cebu.craigslist.com.ph/', 
	u'leeds': u'leeds.craigslist.co.uk/', 
	u'eastern kentucky': u'eastky.craigslist.org/', 
	u'iraq': u'baghdad.craigslist.org/', 
	u'morgantown': u'morgantown.craigslist.org/', 
	u'chongqing': u'chongqing.craigslist.com.cn/', 
	u'ukraine': u'ukraine.craigslist.org/', 
	u'bakersfield': u'bakersfield.craigslist.org/', 
	u'utica-rome-oneida': u'utica.craigslist.org/', 
	u'pretoria': u'pretoria.craigslist.co.za/', 
	u'jaipur': u'jaipur.craigslist.co.in/', 
	u'dublin': u'dublin.craigslist.org/', 
	u'napoli / campania': u'naples.craigslist.it/', 
	u'western maryland': u'westmd.craigslist.org/', 
	u'paris': u'paris.craigslist.org/', 
	u'lima / findlay': u'limaohio.craigslist.org/', 
	u'great falls': u'greatfalls.craigslist.org/', 
	u'derby': u'derby.craigslist.co.uk/', 
	u'dominican republic': u'santodomingo.craigslist.org/', 
	u'bicol region': u'naga.craigslist.com.ph/', 
	u'brownsville': u'brownsville.craigslist.org/', 
	u'las cruces': u'lascruces.craigslist.org/', 
	u'shanghai': u'shanghai.craigslist.com.cn/', 
	u'stockton': u'stockton.craigslist.org/', 
	u'montpellier': u'montpellier.craigslist.org/', 
	u'beijing': u'beijing.craigslist.com.cn/', 
	u'egypt': u'cairo.craigslist.org/', 
	u'nanjing': u'nanjing.craigslist.com.cn/', 
	u'prince edward island': u'pei.craigslist.ca/', 
	u'cedar rapids': u'cedarrapids.craigslist.org/', 
	u'kennewick-pasco-richland': u'kpr.craigslist.org/', 
	u'florence': u'florencesc.craigslist.org/', 
	u'hampton roads': u'norfolk.craigslist.org/', 
	u'jacksonville ': u'onslow.craigslist.org/', 
	u'Europe': u'#EU', 
	u'vienna': u'vienna.craigslist.at/', 
	u'west bank': u'ramallah.craigslist.org/', 
	u'sevilla': u'sevilla.craigslist.es/', 
	u'athens': u'athensga.craigslist.org/', 
	u'territories': u'territories.craigslist.ca/', 
	u'peru': u'lima.craigslist.org/', 
	u'calgary': u'calgary.craigslist.ca/', 
	u'brunswick': u'brunswick.craigslist.org/', 
	u'sarnia': u'sarnia.craigslist.ca/', 
	u'reno / tahoe': u'reno.craigslist.org/', 
	u'southern maryland': u'smd.craigslist.org/', 
	u'provo / orem': u'provo.craigslist.org/', 
	u'fayetteville ': u'fayar.craigslist.org/', 
	u'elmira-corning': u'elmira.craigslist.org/', 
	u'asheville': u'asheville.craigslist.org/', 
	u'northeast SD': u'nesd.craigslist.org/', 
	u'mansfield': u'mansfield.craigslist.org/', 
	u'santa fe / taos': u'santafe.craigslist.org/', 
	u'ahmedabad': u'ahmedabad.craigslist.co.in/', 
	u'glens falls': u'glensfalls.craigslist.org/', 
	u'rockford': u'rockford.craigslist.org/', 
	u'western massachusetts': u'westernmass.craigslist.org/', 
	u'tokyo': u'tokyo.craigslist.jp/', 
	u"st john's": u'newfoundland.craigslist.ca/', 
	u'london': u'london.craigslist.co.uk/', 
	u'ann arbor': u'annarbor.craigslist.org/', 
	u'new hampshire': u'nh.craigslist.org/', 
	u'davao city': u'davaocity.craigslist.com.ph/', 
	u'prince george': u'princegeorge.craigslist.ca/', 
	u'hong kong': u'hongkong.craigslist.hk/', 
	u'hiroshima': u'hiroshima.craigslist.jp/', 
	u'southwest MS': u'natchez.craigslist.org/', 
	u'central louisiana': u'cenla.craigslist.org/', 
	u'tampa bay area': u'tampa.craigslist.org/', 
	u'texarkana': u'texarkana.craigslist.org/', 
	u'southeast KS': u'seks.craigslist.org/', 
	u'show low': u'showlow.craigslist.org/', 
	u'cape town': u'capetown.craigslist.co.za/', 
	u'bend': u'bend.craigslist.org/', 
	u'acapulco': u'acapulco.craigslist.com.mx/', 
	u'college station': u'collegestation.craigslist.org/', 
	u'san francisco bay area': u'sfbay.craigslist.org/', 
	u'hanford-corcoran': u'hanford.craigslist.org/', 
	u'lubbock': u'lubbock.craigslist.org/', 
	u'sioux falls / SE SD': u'siouxfalls.craigslist.org/', 
	u'north platte': u'northplatte.craigslist.org/', 
	u'east idaho': u'eastidaho.craigslist.org/', 
	u'louisville': u'louisville.craigslist.org/', 
	u'catskills': u'catskills.craigslist.org/', 
	u'vancouver': u'vancouver.craigslist.ca/', 
	u'east anglia': u'norwich.craigslist.co.uk/', 
	u'chillicothe': u'chillicothe.craigslist.org/', 
	u'springfield': u'springfield.craigslist.org/', 
	u'edinburgh': u'edinburgh.craigslist.co.uk/', 
	u'seoul': u'seoul.craigslist.co.kr/', 
	u'mankato': u'mankato.craigslist.org/', 
	u'liverpool': u'liverpool.craigslist.co.uk/', 
	u'sardinia': u'sardinia.craigslist.it/', 
	u'valdosta': u'valdosta.craigslist.org/', 
	u'grand forks': u'grandforks.craigslist.org/', 
	u'billings': u'billings.craigslist.org/', 
	u'guam-micronesia': u'micronesia.craigslist.org/', 
	u'ogden-clearfield': u'ogden.craigslist.org/', 
	u'hannover': u'hannover.craigslist.de/', 
	u'sendai': u'sendai.craigslist.jp/', 
	u'ft myers / SW florida': u'fortmyers.craigslist.org/', 
	u'tijuana': u'tijuana.craigslist.com.mx/', 
	u'galveston': u'galveston.craigslist.org/', 
	u'houston': u'houston.craigslist.org/', 
	u'bacolod': u'bacolod.craigslist.com.ph/', 
	u'torino': u'torino.craigslist.it/', 
	u'tallahassee': u'tallahassee.craigslist.org/', 
	u'help': u'www.craigslist.org/about/help/', 
	u'canberra': u'canberra.craigslist.com.au/', 
	u'cardiff / wales': u'cardiff.craigslist.co.uk/', 
	u'valencia': u'valencia.craigslist.es/', 
	u'auburn': u'auburn.craigslist.org/', 
	u'helena': u'helena.craigslist.org/', 
	u'logan': u'logan.craigslist.org/', 
	u'modesto': u'modesto.craigslist.org/', 
	u'hampshire': u'hampshire.craigslist.co.uk/', 
	u'detroit metro': u'detroit.craigslist.org/', 
	u'milwaukee': u'milwaukee.craigslist.org/', 
	u'eau claire': u'eauclaire.craigslist.org/', 
	u'sapporo': u'sapporo.craigslist.jp/', 
	u'chengdu': u'chengdu.craigslist.com.cn/', 
	u'chihuahua': u'chihuahua.craigslist.com.mx/', 
	u'altoona-johnstown': u'altoona.craigslist.org/', 
	u'fairbanks': u'fairbanks.craigslist.org/', 
	u'oneonta': u'oneonta.craigslist.org/', 
	u'denver': u'denver.craigslist.org/', 
	u'new orleans': u'neworleans.craigslist.org/', 
	u'charlottesville': u'charlottesville.craigslist.org/', 
	u'puerto rico': u'puertorico.craigslist.org/', 
	u'norway': u'oslo.craigslist.org/', 
	u'meridian': u'meridian.craigslist.org/', 
	u'eugene': u'eugene.craigslist.org/', 
	u'poconos': u'poconos.craigslist.org/', 
	u'south florida': u'miami.craigslist.org/', 
	u'south bend / michiana': u'southbend.craigslist.org/', 
	u'manila': u'manila.craigslist.com.ph/', 
	u'fukuoka': u'fukuoka.craigslist.jp/', 
	u'fredericksburg': u'fredericksburg.craigslist.org/', 
	u'skagit / island / SJI': u'skagit.craigslist.org/', 
	u'harrisburg': u'harrisburg.craigslist.org/', 
	u'okaloosa / walton': u'okaloosa.craigslist.org/', 
	u'baja california sur': u'bajasur.craigslist.com.mx/', 
	u'flint': u'flint.craigslist.org/', 
	u'oxford': u'oxford.craigslist.co.uk/', 
	u'corvallis/albany': u'corvallis.craigslist.org/', 
	u'toronto': u'toronto.craigslist.ca/', 
	u'susanville': u'susanville.craigslist.org/', 
	u'yellowknife': u'yellowknife.craigslist.ca/', 
	u'south jersey': u'southjersey.craigslist.org/', 
	u'upper peninsula': u'up.craigslist.org/', 
	u'missoula': u'missoula.craigslist.org/', 
	u'saginaw-midland-baycity': u'saginaw.craigslist.org/', 
	u'north jersey': u'newjersey.craigslist.org/', 
	u'redding': u'redding.craigslist.org/', 
	u'genoa': u'genoa.craigslist.it/', 
	u'central NJ': u'cnj.craigslist.org/', 
	u'imperial county': u'imperial.craigslist.org/', 
	u'humboldt county': u'humboldt.craigslist.org/', 
	u'zurich': u'zurich.craigslist.ch/', 
	u'johannesburg': u'johannesburg.craigslist.co.za/', 
	u'state college': u'pennstate.craigslist.org/', 
	u'mazatlan': u'mazatlan.craigslist.com.mx/', 
	u'ciudad juarez': u'juarez.craigslist.com.mx/', 
	u'rochester ': u'rmn.craigslist.org/', 
	u'milan': u'milan.craigslist.it/', 
	u'portland': u'portland.craigslist.org/', 
	u'jackson': u'jackson.craigslist.org/', 
	u'quebec city': u'quebec.craigslist.ca/', 
	u'st petersburg': u'stpetersburg.craigslist.org/', 
	u'texoma': u'texoma.craigslist.org/', 
	u'pensacola': u'pensacola.craigslist.org/', 
	u'goa': u'goa.craigslist.co.in/', 
	u'hangzhou': u'hangzhou.craigslist.com.cn/', 
	u'gulfport / biloxi': u'gulfport.craigslist.org/', 
	u'east oregon': u'eastoregon.craigslist.org/', 
	u'pampanga': u'pampanga.craigslist.com.ph/', 
	u'safety': u'www.craigslist.org/about/scams', 
	u'kent': u'kent.craigslist.co.uk/', 
	u'sacramento': u'sacramento.craigslist.org/', 
	u'eastern montana': u'montana.craigslist.org/', 
	u'venezuela': u'caracas.craigslist.org/', 
	u'cumberland valley': u'chambersburg.craigslist.org/', 
	u'fresno / madera': u'fresno.craigslist.org/', 
	u'durban': u'durban.craigslist.co.za/', 
	u'lawrence': u'lawrence.craigslist.org/', 
	u'hamilton-burlington': u'hamilton.craigslist.ca/', 
	u'essen / ruhr': u'essen.craigslist.de/', 
	u'albuquerque': u'albuquerque.craigslist.org/', 
	u'costa rica': u'costarica.craigslist.org/', 
	u'winston-salem': u'winstonsalem.craigslist.org/', 
	u'port huron': u'porthuron.craigslist.org/', 
	u'southeast alaska': u'juneau.craigslist.org/', 
	u'york': u'york.craigslist.org/', 
	u'shreveport': u'shreveport.craigslist.org/', 
	u'northern WI': u'northernwi.craigslist.org/', 
	u'kenosha-racine': u'racine.craigslist.org/', 
	u'recife': u'recife.craigslist.org/', 
	u'lynchburg': u'lynchburg.craigslist.org/', 
	u'pune': u'pune.craigslist.co.in/', 
	u'cambridge, UK': u'cambridge.craigslist.co.uk/', 
	u'cadiz': u'cadiz.craigslist.es/', 
	u'finland': u'helsinki.craigslist.fi/', 
	u'long island': u'longisland.craigslist.org/', 
	u'bilbao': u'bilbao.craigslist.es/', 
	u'cl jobs': u'www.craigslist.org/about/craigslist_is_hiring', 
	u'belleville': u'belleville.craigslist.ca/', 
	u'fargo / moorhead': u'fargo.craigslist.org/', 
	u'columbus ': u'columbusga.craigslist.org/', 
	u'charleston': u'charleston.craigslist.org/', 
	u'western slope': u'westslope.craigslist.org/', 
	u'austin': u'austin.craigslist.org/', 
	u'finger lakes': u'fingerlakes.craigslist.org/', 
	u'hyderabad': u'hyderabad.craigslist.co.in/', 
	u'romania': u'bucharest.craigslist.org/', 
	u'toulouse': u'toulouse.craigslist.org/', 
	u'shenyang': u'shenyang.craigslist.com.cn/', 
	u'reykjavik': u'reykjavik.craigslist.org/', 
	u'colombia': u'colombia.craigslist.org/', 
	u'new brunswick': u'newbrunswick.craigslist.ca/', 
	u'kitchener-waterloo-cambridge': u'kitchener.craigslist.ca/', 
	u'macon / warner robins': u'macon.craigslist.org/', 
	u'muncie / anderson': u'muncie.craigslist.org/', 
	u'strasbourg': u'strasbourg.craigslist.org/', 
	u'guanajuato': u'guanajuato.craigslist.com.mx/', 
	u'bologna': u'bologna.craigslist.it/', 
	u'sandusky': u'sandusky.craigslist.org/', 
	u'danville': u'danville.craigslist.org/', 
	u'evansville': u'evansville.craigslist.org/', 
	u'victoria ': u'victoriatx.craigslist.org/', 
	u'belo horizonte': u'belohorizonte.craigslist.org/', 
	u'huntsville / decatur': u'huntsville.craigslist.org/', 
	u'geneva': u'geneva.craigslist.ch/', 
	u'pittsburgh': u'pittsburgh.craigslist.org/', 
	u'peoria': u'peoria.craigslist.org/', 
	u'vermont': u'vermont.craigslist.org/', 
	u'cornwall': u'cornwall.craigslist.ca/', 
	u'hartford': u'hartford.craigslist.org/', 
	u'sunshine coast': u'sunshine.craigslist.ca/', 
	u'northwest OK': u'enid.craigslist.org/', 
	u'pullman / moscow': u'pullman.craigslist.org/', 
	u'chatham-kent': u'chatham.craigslist.ca/', 
	u'holland': u'holland.craigslist.org/', 
	u'western IL': u'quincy.craigslist.org/', 
	u'skeena-bulkley': u'skeena.craigslist.ca/', 
	u'indore': u'indore.craigslist.co.in/', 
	u'youngstown': u'youngstown.craigslist.org/', 
	u'sweden': u'stockholm.craigslist.se/', 
	u'tyler / east TX': u'easttexas.craigslist.org/', 
	u'fort dodge': u'fortdodge.craigslist.org/', 
	u'ecuador': u'quito.craigslist.org/', 
	u'rapid city / west SD': u'rapidcity.craigslist.org/', 
	u'prescott': u'prescott.craigslist.org/', 
	u'laredo': u'laredo.craigslist.org/', 
	u'north central FL': u'lakecity.craigslist.org/', 
	u'charlotte': u'charlotte.craigslist.org/', 
	u'dalian': u'dalian.craigslist.com.cn/', 
	u'north dakota': u'nd.craigslist.org/', 
	u'boston': u'boston.craigslist.org/', 
	u'lisbon': u'lisbon.craigslist.pt/', 
	u'trois-rivieres': u'troisrivieres.craigslist.ca/', 
	u'tuscaloosa': u'tuscaloosa.craigslist.org/', 
	u'lake of the ozarks': u'loz.craigslist.org/', 
	u'windsor': u'windsor.craigslist.ca/', 
	u'caribbean islands': u'caribbean.craigslist.org/', 
	u'central michigan': u'centralmich.craigslist.org/', 
	u'rochester': u'rochester.craigslist.org/', 
	u'abilene': u'abilene.craigslist.org/', 
	u'san diego': u'sandiego.craigslist.org/', 
	u'lafayette / west lafayette': u'tippecanoe.craigslist.org/', 
	u'montgomery': u'montgomery.craigslist.org/', 
	u'santa maria': u'santamaria.craigslist.org/', 
	u'grand rapids': u'grandrapids.craigslist.org/', 
	u'fort smith': u'fortsmith.craigslist.org/', 
	u'yakima': u'yakima.craigslist.org/', 
	u'grand island': u'grandisland.craigslist.org/', 
	u'jersey shore': u'jerseyshore.craigslist.org/', 
	u'clovis / portales': u'clovis.craigslist.org/', 
	u"xi'an": u'xian.craigslist.com.cn/', 
	u'victoria': u'victoria.craigslist.ca/', 
	u'flagstaff / sedona': u'flagstaff.craigslist.org/', 
	u'northern panhandle': u'wheeling.craigslist.org/', 
	u'southern WV': u'swv.craigslist.org/', 
	u'eastern shore': u'easternshore.craigslist.org/', 
	u'deep east texas': u'nacogdoches.craigslist.org/', 
	u'haifa': u'haifa.craigslist.org/', 
	u'battle creek': u'battlecreek.craigslist.org/', 
	u'mobile': u'mobile.craigslist.org/', 
	u'frederick': u'frederick.craigslist.org/', 
	u'kaiserslautern': u'kaiserslautern.craigslist.de/', 
	u'yucatan': u'yucatan.craigslist.com.mx/', 
	u'los angeles': u'losangeles.craigslist.org/', 
	u'bordeaux': u'bordeaux.craigslist.org/', 
	u'high rockies': u'rockies.craigslist.org/', 
	u'monterey bay': u'monterey.craigslist.org/', 
	u'new river valley': u'blacksburg.craigslist.org/', 
	u'madison': u'madison.craigslist.org/', 
	u'knoxville': u'knoxville.craigslist.org/', 
	u'kolkata (calcutta)': u'kolkata.craigslist.co.in/', 
	u'hudson valley': u'hudsonvalley.craigslist.org/', 
	u'sarasota-bradenton': u'sarasota.craigslist.org/', 
	u"nice / cote d'azur": u'cotedazur.craigslist.org/', 
	u'manchester': u'manchester.craigslist.co.uk/', 
	u'nagoya': u'nagoya.craigslist.jp/', 
	u'baleares': u'baleares.craigslist.es/', 
	u'champaign urbana': u'chambana.craigslist.org/', 
	u'feedback': u'https:forums.craigslist.org/?forumID=8', 
	u'bern': u'bern.craigslist.ch/', 
	u'kelowna / okanagan': u'kelowna.craigslist.ca/', 
	u'mumbai': u'mumbai.craigslist.co.in/', 
	u'faro / algarve': u'faro.craigslist.pt/', 
	u'basel': u'basel.craigslist.ch/', 
	u'cookeville': u'cookeville.craigslist.org/', 
	u'lansing': u'lansing.craigslist.org/', 
	u'brisbane': u'brisbane.craigslist.com.au/', 
	u'parkersburg-marietta': u'parkersburg.craigslist.org/', 
	u'darwin': u'darwin.craigslist.com.au/', 
	u'southwest VA': u'swva.craigslist.org/', 
	u'hilton head': u'hiltonhead.craigslist.org/', 
	u'boulder': u'boulder.craigslist.org/', 
	u'lake charles': u'lakecharles.craigslist.org/', 
	u'florence / muscle shoals': u'shoals.craigslist.org/', 
	u'new york city': u'newyork.craigslist.org/', 
	u'dayton / springfield': u'dayton.craigslist.org/', 
	u'nuremberg': u'nuremberg.craigslist.de/', 
	u'guatemala': u'guatemala.craigslist.org/', 
	u'lewiston / clarkston': u'lewiston.craigslist.org/', 
	u'lethbridge': u'lethbridge.craigslist.ca/', 
	u'rhode island': u'providence.craigslist.org/', 
	u'st louis': u'stlouis.craigslist.org/', 
	u'budapest': u'budapest.craigslist.org/', 
	u'athens ': u'athensohio.craigslist.org/', 
	u'south coast': u'southcoast.craigslist.org/', 
	u'wilmington': u'wilmington.craigslist.org/', 
	u'lexington': u'lexington.craigslist.org/', 
	u'terre haute': u'terrehaute.craigslist.org/', 
	u'privacy': u'www.craigslist.org/about/privacy.policy', 
	u'kirksville': u'kirksville.craigslist.org/', 
	u'springfield ': u'springfieldil.craigslist.org/', 
	u'croatia': u'zagreb.craigslist.org/', 
	u'salt lake city': u'saltlakecity.craigslist.org/', 
	u'northwest KS': u'nwks.craigslist.org/', 
	u'dunedin': u'dunedin.craigslist.co.nz/', 
	u'bulgaria': u'bulgaria.craigslist.org/', 
	u'kalamazoo': u'kalamazoo.craigslist.org/', 
	u'odessa / midland': u'odessa.craigslist.org/', 
	u'mcallen / edinburg': u'mcallen.craigslist.org/', 
	u'ottawa-hull-gatineau': u'ottawa.craigslist.ca/', 
	u'prague': u'prague.craigslist.cz/', 
	u'florence / tuscany': u'florence.craigslist.it/', 
	u'cologne': u'cologne.craigslist.de/', 
	u'cairns': u'cairns.craigslist.com.au/', 
	u'broward county': u'miami.craigslist.org/brw', 
	u'greece': u'athens.craigslist.gr/', 
	u'iran': u'tehran.craigslist.org/', 
	u'roseburg': u'roseburg.craigslist.org/', 
	u'aberdeen': u'aberdeen.craigslist.co.uk/', 
	u'hattiesburg': u'hattiesburg.craigslist.org/', 
	u'lancaster': u'lancaster.craigslist.org/', 
	u'fort lauderdale': u'fortlauderdale.craigslist.org/', 
	u'lyon': u'lyon.craigslist.org/', 
	u'ocala': u'ocala.craigslist.org/', 
	u'wichita falls': u'wichitafalls.craigslist.org/', 
	u'medford-ashland': u'medford.craigslist.org/', 
	u'scottsbluff / panhandle': u'scottsbluff.craigslist.org/', 
	u'ithaca': u'ithaca.craigslist.org/', 
	u'st joseph': u'stjoseph.craigslist.org/', 
	u'dundee': u'dundee.craigslist.co.uk/', 
	u'anchorage / mat-su': u'anchorage.craigslist.org/', 
	u'cagayan de oro': u'cdo.craigslist.com.ph/', 
	u'toledo': u'toledo.craigslist.org/', 
	u'reading': u'reading.craigslist.org/', 
	u'glasgow': u'glasgow.craigslist.co.uk/', 
	u'yuma': u'yuma.craigslist.org/', 
	u'zanesville / cambridge': u'zanesville.craigslist.org/', 
	u'terms': u'www.craigslist.org/about/terms.of.use', 
	u'united arab emirates': u'dubai.craigslist.org/', 
	u'nashville': u'nashville.craigslist.org/', 
	u'boise': u'boise.craigslist.org/', 
	u'butte': u'butte.craigslist.org/', 
	u'ames': u'ames.craigslist.org/', 
	u'marseille': u'marseilles.craigslist.org/', 
	u'inland empire': u'inlandempire.craigslist.org/', 
	u'killeen / temple / ft hood': u'killeen.craigslist.org/', 
	u'saskatoon': u'saskatoon.craigslist.ca/', 
	u'stuttgart': u'stuttgart.craigslist.de/', 
	u'kenai peninsula': u'kenai.craigslist.org/', 
	u'las vegas': u'lasvegas.craigslist.org/', 
	u'normandy': u'rouen.craigslist.org/', 
	u'statesboro': u'statesboro.craigslist.org/', 
	u'lawton': u'lawton.craigslist.org/', 
	u'outer banks': u'outerbanks.craigslist.org/', 
	u'baltimore': u'baltimore.craigslist.org/', 
	u'sierra vista': u'sierravista.craigslist.org/', 
	u'lehigh valley': u'allentown.craigslist.org/', 
	u'tunisia': u'tunis.craigslist.org/', 
	u'leipzig': u'leipzig.craigslist.de/', 
	u'moscow': u'moscow.craigslist.org/', 
	u'chennai (madras)': u'chennai.craigslist.co.in/', 
	u'peace river country': u'peace.craigslist.ca/', 
	u'san luis obispo': u'slo.craigslist.org/', 
	u'owensboro': u'owensboro.craigslist.org/', 
	u'meadville': u'meadville.craigslist.org/', 
	u'sao paulo': u'saopaulo.craigslist.org/', 
	u'southeast IA': u'ottumwa.craigslist.org/', 
	u'siskiyou county': u'siskiyou.craigslist.org/', 
	u'turkey': u'istanbul.craigslist.com.tr/', 
	u'buenos aires': u'buenosaires.craigslist.org/', 
	u'winnipeg': u'winnipeg.craigslist.ca/', 
	u'treasure coast': u'treasure.craigslist.org/', 
	u'newcastle, NSW': u'ntl.craigslist.com.au/', 
	u'corpus christi': u'corpuschristi.craigslist.org/', 
	u'bhubaneswar': u'bhubaneswar.craigslist.co.in/', 
	u'tuscarawas co': u'tuscarawas.craigslist.org/', 
	u'veracruz': u'veracruz.craigslist.com.mx/', 
	u'chandigarh': u'chandigarh.craigslist.co.in/', 
	u'fraser valley': u'abbotsford.craigslist.ca/', 
	u'williamsport': u'williamsport.craigslist.org/', 
	u'chile': u'santiago.craigslist.org/', 
	u'hamburg': u'hamburg.craigslist.de/', 
	u'atlanta': u'atlanta.craigslist.org/', 
	u'stillwater': u'stillwater.craigslist.org/', 
	u'mason city': u'masoncity.craigslist.org/', 
	u'coventry': u'coventry.craigslist.co.uk/', 
	u'brasilia': u'brasilia.craigslist.org/', 
	u'bowling green': u'bgky.craigslist.org/', 
	u'bemidji': u'bemidji.craigslist.org/', 
	u'des moines': u'desmoines.craigslist.org/', 
	u'oklahoma city': u'oklahomacity.craigslist.org/', 
	u'northwest GA': u'nwga.craigslist.org/', 
	u'heartland florida': u'cfl.craigslist.org/', 
	u'green bay': u'greenbay.craigslist.org/', 
	u'iowa city': u'iowacity.craigslist.org/', 
	u'frankfurt': u'frankfurt.craigslist.de/', 
	u'kenya': u'kenya.craigslist.org/', 
	u'monroe': u'monroe.craigslist.org/', 
	u'albany': u'albany.craigslist.org/', 
	u'medicine hat': u'hat.craigslist.ca/', 
	u'salina': u'salina.craigslist.org/', 
	u'sicilia': u'sicily.craigslist.it/', 
	u'kalispell': u'kalispell.craigslist.org/', 
	u'annapolis': u'annapolis.craigslist.org/', 
	u'omaha / council bluffs': u'omaha.craigslist.org/', 
	u'guadalajara': u'guadalajara.craigslist.com.mx/', 
	u'ethiopia': u'addisababa.craigslist.org/', 
	u'surat surat': u'surat.craigslist.co.in/', 
	u'myrtle beach': u'myrtlebeach.craigslist.org/', 
	u'ashtabula': u'ashtabula.craigslist.org/', 
	u'cape cod / islands': u'capecod.craigslist.org/', 
	u'visalia-tulare': u'visalia.craigslist.org/', 
	u'ventura county': u'ventura.craigslist.org/', 
	u'chautauqua': u'chautauqua.craigslist.org/', 
	u'mexico city': u'mexicocity.craigslist.com.mx/', 
	u'southern illinois': u'carbondale.craigslist.org/', 
	u'indianapolis': u'indianapolis.craigslist.org/', 
	u'columbia': u'columbia.craigslist.org/', 
	u'bristol': u'bristol.craigslist.co.uk/', 
	u'singapore': u'singapore.craigslist.com.sg/', 
	u'akron / canton': u'akroncanton.craigslist.org/', 
	u'kansas city': u'kansascity.craigslist.org/', 
	u'houma': u'houma.craigslist.org/', 
	u'gold country': u'goldcountry.craigslist.org/', 
	u'sheboygan': u'sheboygan.craigslist.org/', 
	u'chattanooga': u'chattanooga.craigslist.org/', 
	u'malaga': u'malaga.craigslist.es/', 
	u'el salvador': u'elsalvador.craigslist.org/', 
	u'poland': u'warsaw.craigslist.pl/', 
	u'indonesia': u'jakarta.craigslist.org/', 
	u'wellington': u'wellington.craigslist.org/', 
	u'el paso': u'elpaso.craigslist.org/', 
	u'augusta': u'augusta.craigslist.org/', 
	u'montreal': u'montreal.craigslist.ca/', 
	u'southwest KS': u'swks.craigslist.org/', 
	u'twin falls': u'twinfalls.craigslist.org/', 
	u'saguenay': u'saguenay.craigslist.ca/', 
	u'greenville / upstate': u'greenville.craigslist.org/', 
	u'pakistan': u'pakistan.craigslist.org/', 
	u'perugia': u'perugia.craigslist.it/', 
	u'edmonton': u'edmonton.craigslist.ca/', 
	u'oregon coast': u'oregoncoast.craigslist.org/', 
	u'bremen': u'bremen.craigslist.de/', 
	u'belgium': u'brussels.craigslist.org/', 
	u'birmingham': u'bham.craigslist.org/', 
	u'hermosillo': u'hermosillo.craigslist.com.mx/', 
	u'appleton-oshkosh-FDL': u'appleton.craigslist.org/', 
	u'auckland': u'auckland.craigslist.org/', 
	u'taiwan': u'taipei.craigslist.com.tw/', 
	u'pierre / central SD': u'csd.craigslist.org/', 
	u'yuba-sutter': u'yubasutter.craigslist.org/', 
	u'puerto vallarta': u'pv.craigslist.com.mx/', 
	u'twin tiers NY/PA': u'twintiers.craigslist.org/', 
	u'beaumont / port arthur': u'beaumont.craigslist.org/', 
	u'belfast': u'belfast.craigslist.co.uk/', 
	u'winchester': u'winchester.craigslist.org/', 
	u'plattsburgh-adirondacks': u'plattsburgh.craigslist.org/', 
	u'eastern CO': u'eastco.craigslist.org/', 
	u'clarksville': u'clarksville.craigslist.org/', 
	u'niagara region': u'niagara.craigslist.ca/', 
	u'kerala': u'kerala.craigslist.co.in/', 
	u'kokomo': u'kokomo.craigslist.org/', 
	u'perth': u'perth.craigslist.com.au/', 
	u'sydney': u'sydney.craigslist.com.au/', 
	u'eastern CT': u'newlondon.craigslist.org/', 
	u'heidelberg': u'heidelberg.craigslist.de/', 
	u'porto': u'porto.craigslist.pt/', 
	u'delhi': u'delhi.craigslist.co.in/', 
	u'munich': u'munich.craigslist.de/', 
	u'amarillo': u'amarillo.craigslist.org/', 
	u'worcester / central MA': u'worcester.craigslist.org/', 
	u'jonesboro': u'jonesboro.craigslist.org/', 
	u'tel aviv': u'telaviv.craigslist.org/', 
	u'grenoble': u'grenoble.craigslist.org/', 
	u'jacksonville': u'jacksonville.craigslist.org/', 
	u'Latin America': u'#LATAM', 
	u'potsdam-canton-massena': u'potsdam.craigslist.org/', 
	u'lincoln': u'lincoln.craigslist.org/', 
	u'northwest CT': u'nwct.craigslist.org/', 
	u'baton rouge': u'batonrouge.craigslist.org/', 
	u'orlando': u'orlando.craigslist.org/', 
	u'dusseldorf': u'dusseldorf.craigslist.de/', 
	u'san antonio': u'sanantonio.craigslist.org/', 
	u'oaxaca': u'oaxaca.craigslist.com.mx/', 
	u'birmingham / west mids': u'birmingham.craigslist.co.uk/', 
	u'mattoon-charleston': u'mattoon.craigslist.org/', 
	u'chico': u'chico.craigslist.org/', 
	u'olympic peninsula': u'olympic.craigslist.org/', 
	u'jackson ': u'jxn.craigslist.org/', 
	u'Oceania': u'#OCEANIA', 
	u'miami / dade': u'miami.craigslist.org/mdc', 
	u'brainerd': u'brainerd.craigslist.org/', 
	u'Asia/Pacific/Middle East': u'#ASIA', 
	u'elko': u'elko.craigslist.org/', 
	u'hickory / lenoir': u'hickory.craigslist.org/', 
	u'london ': u'londonon.craigslist.ca/', 
	u'cleveland': u'cleveland.craigslist.org/', 
	u'halifax': u'halifax.craigslist.ca/', 
	u'raleigh / durham / CH': u'raleigh.craigslist.org/', 
	u'nicaragua': u'managua.craigslist.org/', 
	u'regina': u'regina.craigslist.ca/', 
	u'new haven': u'newhaven.craigslist.org/', 
	u'wollongong': u'wollongong.craigslist.com.au/', 
	u'delaware': u'delaware.craigslist.org/', 
	u'luxembourg': u'luxembourg.craigslist.org/', 
	u'whitehorse': u'whitehorse.craigslist.ca/', 
	u'fort wayne': u'fortwayne.craigslist.org/', 
	u'san angelo': u'sanangelo.craigslist.org/', 
	u'monterrey': u'monterrey.craigslist.com.mx/', 
	u'columbus': u'columbus.craigslist.org/', 
	u'fort collins / north CO': u'fortcollins.craigslist.org/', 
	u'western KY': u'westky.craigslist.org/', 
	u'st augustine': u'staugustine.craigslist.org/', 
	u'palm beach county': u'miami.craigslist.org/pbc', 
	u'fortaleza': u'fortaleza.craigslist.org/', 
	u'binghamton': u'binghamton.craigslist.org/', 
	u'barrie': u'barrie.craigslist.ca/', 
	u'thailand': u'bangkok.craigslist.co.th/', 
	u'bangalore': u'bangalore.craigslist.co.in/', 
	u'decatur': u'decatur.craigslist.org/', 
	u'brighton': u'brighton.craigslist.co.uk/', 
	u'about': u'www.craigslist.org/about/', 
	u'gadsden-anniston': u'gadsden.craigslist.org/', 
	u'brittany': u'rennes.craigslist.org/', 
	u'US': u'#US', 
	u'monroe ': u'monroemi.craigslist.org/', 
	u'melbourne': u'melbourne.craigslist.com.au/', 
	u'topeka': u'topeka.craigslist.org/', 
	u'whistler': u'whistler.craigslist.ca/', 
	u'joplin': u'joplin.craigslist.org/', 
	u'quad cities': u'quadcities.craigslist.org/', 
	u'greensboro': u'greensboro.craigslist.org/', 
	u'eastern NC': u'eastnc.craigslist.org/', 
	u'mohave county': u'mohave.craigslist.org/', 
	u'U.S. virgin islands': u'virgin.craigslist.org/', 
	u'washington': u'washingtondc.craigslist.org/', 
	u'essex': u'essex.craigslist.co.uk/', 
	u'bath': u'bath.craigslist.co.uk/', 
	u'waterloo / cedar falls': u'waterloo.craigslist.org/', 
	u'bloomington-normal': u'bn.craigslist.org/', 
	u'jerusalem': u'jerusalem.craigslist.org/', 
	u'red deer': u'reddeer.craigslist.ca/', 
	u'eastern panhandle': u'martinsburg.craigslist.org/', 
	u'south dakota': u'sd.craigslist.org/', 
	u'del rio / eagle pass': u'delrio.craigslist.org/', 
	u'waco': u'waco.craigslist.org/', 
	u'philadelphia': u'philadelphia.craigslist.org/', 
	u'daytona beach': u'daytona.craigslist.org/', 
	u'sioux city': u'siouxcity.craigslist.org/', 
	u'owen sound': u'owensound.craigslist.ca/', 
	u'madrid': u'madrid.craigslist.es/', 
	u'bloomington': u'bloomington.craigslist.org/', 
	u'minneapolis / st paul': u'minneapolis.craigslist.org/', 
	u'bolivia': u'lapaz.craigslist.org/', 
	u'klamath falls': u'klamath.craigslist.org/', 
	u'palm springs': u'palmsprings.craigslist.org/', 
	u'curitiba': u'curitiba.craigslist.org/', 
	u'brantford-woodstock': u'brantford.craigslist.ca/', 
	u'kingston': u'kingston.craigslist.ca/', 
	u'rio de janeiro': u'rio.craigslist.org/', 
	u'iloilo': u'iloilo.craigslist.com.ph/', 
	u'southeast missouri': u'semo.craigslist.org/', 
	u"spokane / coeur d'alene": u'spokane.craigslist.org/', 
	u'porto alegre': u'portoalegre.craigslist.org/', 
	u'tasmania': u'hobart.craigslist.com.au/', 
	u'la crosse': u'lacrosse.craigslist.org/', 
	u'memphis': u'memphis.craigslist.org/', 
	u'st cloud': u'stcloud.craigslist.org/', 
	u'sault ste marie': u'soo.craigslist.ca/', 
	u'malaysia': u'malaysia.craigslist.org/', 
	u'Africa': u'#AF', 
	u'morocco': u'casablanca.craigslist.org/', 
	u'tucson': u'tucson.craigslist.org/', 
	u'san marcos': u'sanmarcos.craigslist.org/', 
	u'wenatchee': u'wenatchee.craigslist.org/', 
	u'sudbury': u'sudbury.craigslist.ca/', 
	u'newcastle / NE england': u'newcastle.craigslist.co.uk/', 
	u'wichita': u'wichita.craigslist.org/', 
	u'janesville': u'janesville.craigslist.org/', 
	u'little rock': u'littlerock.craigslist.org/', 
	u'rome': u'rome.craigslist.it/', 
	u'salem': u'salem.craigslist.org/', 
	u'seattle-tacoma': u'seattle.craigslist.org/', 
	u'west virginia (old)': u'wv.craigslist.org/', 
	u'panama city': u'panamacity.craigslist.org/', 
	u'erie': u'erie.craigslist.org/', 
	u'zamboanga': u'zamboanga.craigslist.com.ph/', 
	u'adelaide': u'adelaide.craigslist.com.au/', 
	u'lausanne': u'lausanne.craigslist.ch/', 
	u'granada': u'granada.craigslist.es/', 
	u'peterborough': u'peterborough.craigslist.ca/', 
	u'gainesville': u'gainesville.craigslist.org/', 
	u'thunder bay': u'thunderbay.craigslist.ca/', 
	u'northern michigan': u'nmi.craigslist.org/', 
	u'manhattan': u'ksu.craigslist.org/', 
	u'shenzhen': u'shenzhen.craigslist.com.cn/', 
	u'phoenix': u'phoenix.craigslist.org/', 
	u'st george': u'stgeorge.craigslist.org/', 
	u'amsterdam / randstad': u'amsterdam.craigslist.org/', 
	u'dubuque': u'dubuque.craigslist.org/', 
	u'florida keys': u'keys.craigslist.org/', 
	u'savannah / hinesville': u'savannah.craigslist.org/', 
	u'southwest michigan': u'swmi.craigslist.org/', 
	u'cariboo': u'cariboo.craigslist.ca/', 
	u'roswell / carlsbad': u'roswell.craigslist.org/', 
	u'lakeland': u'lakeland.craigslist.org/', 
	u'berlin': u'berlin.craigslist.de/', 
	u'barcelona': u'barcelona.craigslist.es/', 
	u'watertown': u'watertown.craigslist.org/', 
	u'jackson  ': u'jacksontn.craigslist.org/', 
	u'vietnam': u'vietnam.craigslist.org/', 
	u'lafayette': u'lafayette.craigslist.org/', 
	u'boone': u'boone.craigslist.org/', 
	u'kuwait': u'kuwait.craigslist.org/', 
	u'fayetteville': u'fayetteville.craigslist.org/', 
	u'comox valley': u'comoxvalley.craigslist.ca/', 
	u'buffalo': u'buffalo.craigslist.org/', 
	u'santa barbara': u'santabarbara.craigslist.org/', 
	u'charleston ': u'charlestonwv.craigslist.org/'
}
